# Update -> Replace current template -> Upload a template file -> Choose file
# IMPORTANT: Update requires<No interruption|Some interruption|Replacement>

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0e047ce9149262f82"
      InstanceType: "t2.micro"
      # update tags
      Tags:
        - Key: "Label"
          Value: "ec2-from-cloudformation"
        - Key: "Env"
          Value: "lab"
